import { EmployeePerformance } from "@/types/employee";

export const employees: EmployeePerformance[] = [
  {
    id: "EMP-014",
    name: "Jordan Shaw",
    role: "Senior Filing Specialist",
    tasksCompleted: 142,
    tasksOnTime: 138,
    avgCompletionHours: 3.2,
    trend: "up",
    trendValue: "+4%",
  },
  {
    id: "EMP-022",
    name: "Maria Lopez",
    role: "Compliance Analyst",
    tasksCompleted: 128,
    tasksOnTime: 121,
    avgCompletionHours: 4.1,
    trend: "up",
    trendValue: "+2%",
  },
  {
    id: "EMP-009",
    name: "David Kim",
    role: "Filing Specialist",
    tasksCompleted: 156,
    tasksOnTime: 132,
    avgCompletionHours: 6.5,
    trend: "down",
    trendValue: "-6%",
  },
  {
    id: "EMP-031",
    name: "Priya Nair",
    role: "Senior Compliance Analyst",
    tasksCompleted: 119,
    tasksOnTime: 116,
    avgCompletionHours: 3.8,
    trend: "flat",
    trendValue: "0%",
  },
  {
    id: "EMP-017",
    name: "Ethan Brooks",
    role: "Filing Specialist",
    tasksCompleted: 97,
    tasksOnTime: 74,
    avgCompletionHours: 8.9,
    trend: "down",
    trendValue: "-9%",
  },
  {
    id: "EMP-005",
    name: "Sofia Reyes",
    role: "Registration Coordinator",
    tasksCompleted: 134,
    tasksOnTime: 129,
    avgCompletionHours: 4.4,
    trend: "up",
    trendValue: "+3%",
  },
];